
services:
  nginx:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports: 
      - 8080:80
  backend:
    build: backend
    volumes:
      - git-repos:/app/gitrepos/
    expose:
      - 8000
    depends_on:
      - postgres
  gitserver:
    image: rockstorm/git-server
    volumes:
      - git-repos:/srv/git
    ports:
      - 2222:22
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=pwd"
      - "POSTGRES_USER=pgusr"
volumes:
  git-repos: