
services:
  nginx:
    image: nginx
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports: 
      - 8080:80
  backend:
    build: backend
    volumes:
      - git-repos:/app/gitrepos/
    expose:
      - 8000
    ports:
      - 7777:8000
    environment:
      - UVICORN_HOST=0.0.0.0
      - DB_LOGIN=pgusr
      - DB_PASSWORD=pwd
      - DB_NAME=scufdb
      - DB_ADDR=postgres
    depends_on:
      - postgres
  gitserver:
    image: rockstorm/git-server
    volumes:
      - git-repos:/srv/git
    ports:
      - 2222:22
  postgres:
    image: postgres
    environment:
      - "POSTGRES_PASSWORD=pwd"
      - "POSTGRES_USER=pgusr"
      - "POSTGRES_DB=scufdb"
volumes:
  git-repos: